# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rand_int.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NumeroRandom(object):
    def setupUi(self, NumeroRandom):
        NumeroRandom.setObjectName("NumeroRandom")
        NumeroRandom.resize(510, 455)
        NumeroRandom.setMinimumSize(QtCore.QSize(300, 200))
        self.centralwidget = QtWidgets.QWidget(NumeroRandom)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 491, 411))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabNumber = QtWidgets.QWidget()
        self.tabNumber.setObjectName("tabNumber")
        self.label_respuesta = QtWidgets.QLabel(self.tabNumber)
        self.label_respuesta.setGeometry(QtCore.QRect(120, 210, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_respuesta.setFont(font)
        self.label_respuesta.setText("")
        self.label_respuesta.setObjectName("label_respuesta")
        self.line = QtWidgets.QFrame(self.tabNumber)
        self.line.setGeometry(QtCore.QRect(10, 150, 461, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.genera_button = QtWidgets.QPushButton(self.tabNumber)
        self.genera_button.setGeometry(QtCore.QRect(20, 210, 89, 25))
        self.genera_button.setAutoDefault(False)
        self.genera_button.setDefault(False)
        self.genera_button.setFlat(False)
        self.genera_button.setObjectName("genera_button")
        self.formLayoutWidget = QtWidgets.QWidget(self.tabNumber)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 10, 431, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_inferior = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_inferior.setFont(font)
        self.label_inferior.setObjectName("label_inferior")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_inferior)
        self.spinBox_inferior = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_inferior.setMinimum(-99999)
        self.spinBox_inferior.setMaximum(99999)
        self.spinBox_inferior.setObjectName("spinBox_inferior")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_inferior)
        self.label_superior = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_superior.setFont(font)
        self.label_superior.setObjectName("label_superior")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_superior)
        self.spinBox_superior = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_superior.setMinimum(-99999)
        self.spinBox_superior.setMaximum(99999)
        self.spinBox_superior.setProperty("value", 10)
        self.spinBox_superior.setObjectName("spinBox_superior")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_superior)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.tabWidget.addTab(self.tabNumber, "")
        self.tabList = QtWidgets.QWidget()
        self.tabList.setObjectName("tabList")
        self.textEdit = QtWidgets.QPlainTextEdit(self.tabList)
        self.textEdit.setGeometry(QtCore.QRect(20, 10, 431, 291))
        self.textEdit.setObjectName("textEdit")
        self.line_2 = QtWidgets.QFrame(self.tabList)
        self.line_2.setGeometry(QtCore.QRect(10, 310, 461, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButtonList = QtWidgets.QPushButton(self.tabList)
        self.pushButtonList.setGeometry(QtCore.QRect(20, 340, 101, 25))
        self.pushButtonList.setObjectName("pushButtonList")
        self.labelList = QtWidgets.QLabel(self.tabList)
        self.labelList.setGeometry(QtCore.QRect(140, 340, 331, 17))
        self.labelList.setText("")
        self.labelList.setObjectName("labelList")
        self.tabWidget.addTab(self.tabList, "")
        NumeroRandom.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(NumeroRandom)
        self.statusbar.setObjectName("statusbar")
        NumeroRandom.setStatusBar(self.statusbar)

        self.retranslateUi(NumeroRandom)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NumeroRandom)

    def retranslateUi(self, NumeroRandom):
        _translate = QtCore.QCoreApplication.translate
        NumeroRandom.setWindowTitle(_translate("NumeroRandom", "Generador Random"))
        self.genera_button.setText(_translate("NumeroRandom", "Genera"))
        self.genera_button.setShortcut(_translate("NumeroRandom", "Return"))
        self.label_inferior.setText(_translate("NumeroRandom", "Lím. Inferior"))
        self.label_superior.setText(_translate("NumeroRandom", "Lím. Superior"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNumber), _translate("NumeroRandom", "Número"))
        self.pushButtonList.setText(_translate("NumeroRandom", "Escoge"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabList), _translate("NumeroRandom", "Lista"))
