# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rand_int.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RandomGeneratorWindow(object):
    def setupUi(self, RandomGeneratorWindow):
        RandomGeneratorWindow.setObjectName("RandomGeneratorWindow")
        RandomGeneratorWindow.resize(510, 455)
        RandomGeneratorWindow.setMinimumSize(QtCore.QSize(300, 200))
        self.centralwidget = QtWidgets.QWidget(RandomGeneratorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 501, 411))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabNumber = QtWidgets.QWidget()
        self.tabNumber.setObjectName("tabNumber")
        self.labelNumber = QtWidgets.QLabel(self.tabNumber)
        self.labelNumber.setGeometry(QtCore.QRect(120, 210, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelNumber.setFont(font)
        self.labelNumber.setText("")
        self.labelNumber.setObjectName("labelNumber")
        self.line = QtWidgets.QFrame(self.tabNumber)
        self.line.setGeometry(QtCore.QRect(10, 150, 461, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButtonNumber = QtWidgets.QPushButton(self.tabNumber)
        self.pushButtonNumber.setGeometry(QtCore.QRect(20, 210, 89, 25))
        self.pushButtonNumber.setAutoDefault(False)
        self.pushButtonNumber.setDefault(False)
        self.pushButtonNumber.setFlat(False)
        self.pushButtonNumber.setObjectName("pushButtonNumber")
        self.formLayoutWidget = QtWidgets.QWidget(self.tabNumber)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 10, 431, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelLower = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelLower.setFont(font)
        self.labelLower.setObjectName("labelLower")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelLower)
        self.spinBoxLower = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxLower.setMinimum(-99999)
        self.spinBoxLower.setMaximum(99999)
        self.spinBoxLower.setProperty("value", 1)
        self.spinBoxLower.setObjectName("spinBoxLower")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBoxLower)
        self.labelUpper = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelUpper.setFont(font)
        self.labelUpper.setObjectName("labelUpper")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelUpper)
        self.spinBoxUpper = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxUpper.setMinimum(-99999)
        self.spinBoxUpper.setMaximum(99999)
        self.spinBoxUpper.setProperty("value", 10)
        self.spinBoxUpper.setObjectName("spinBoxUpper")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxUpper)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.tabWidget.addTab(self.tabNumber, "")
        self.tabList = QtWidgets.QWidget()
        self.tabList.setObjectName("tabList")
        self.textEditList = QtWidgets.QPlainTextEdit(self.tabList)
        self.textEditList.setGeometry(QtCore.QRect(20, 10, 431, 291))
        self.textEditList.setObjectName("textEditList")
        self.line_2 = QtWidgets.QFrame(self.tabList)
        self.line_2.setGeometry(QtCore.QRect(10, 310, 461, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButtonList = QtWidgets.QPushButton(self.tabList)
        self.pushButtonList.setGeometry(QtCore.QRect(20, 340, 101, 25))
        self.pushButtonList.setObjectName("pushButtonList")
        self.labelList = QtWidgets.QLabel(self.tabList)
        self.labelList.setGeometry(QtCore.QRect(140, 340, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelList.setFont(font)
        self.labelList.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.labelList.setText("")
        self.labelList.setWordWrap(True)
        self.labelList.setObjectName("labelList")
        self.tabWidget.addTab(self.tabList, "")
        RandomGeneratorWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RandomGeneratorWindow)
        self.statusbar.setObjectName("statusbar")
        RandomGeneratorWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RandomGeneratorWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RandomGeneratorWindow)

    def retranslateUi(self, RandomGeneratorWindow):
        _translate = QtCore.QCoreApplication.translate
        RandomGeneratorWindow.setWindowTitle(_translate("RandomGeneratorWindow", "Random Generator"))
        self.pushButtonNumber.setText(_translate("RandomGeneratorWindow", "Generate"))
        self.pushButtonNumber.setShortcut(_translate("RandomGeneratorWindow", "Return"))
        self.labelLower.setText(_translate("RandomGeneratorWindow", "Lower Limit"))
        self.labelUpper.setText(_translate("RandomGeneratorWindow", "Upper Limit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNumber), _translate("RandomGeneratorWindow", "Number"))
        self.pushButtonList.setText(_translate("RandomGeneratorWindow", "Choose"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabList), _translate("RandomGeneratorWindow", "From List"))
